-- This script creates a .sql file consisting of DELETE and INSERT statements to
-- replace the contents of the DMV tables in an Oracle database.  
-- It is meant to be run against the DMV tables that have been populated with data

set echo off newpage 0 space 0 pagesize 0 feed off head off trimspool on LIN 1024
spool dmv_insert_template_oracle.sql

SELECT '-- Autogenerated from dmv_insert_util_oracle.sql' from dual;
SELECT 'DELETE FROM vehicle_owner;' from dual;
SELECT 'DELETE FROM vehicle_registration;' from dual;
SELECT 'DELETE FROM residence;' from dual;
SELECT 'DELETE FROM location;' from dual;
SELECT 'DELETE FROM physical_details;' from dual;
SELECT 'DELETE FROM person;' from dual;

SELECT 'ALTER SESSION SET NLS_DATE_FORMAT=''DD-MON-YYYY HH:MI:SS'';' from dual;

ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH:MI:SS';

SELECT 'INSERT INTO location VALUES (''' || id || ''',''' || REPLACE(street_no,'''', '''''') || ''',''' || REPLACE(street_name,'''', '''''') || ''',''' || REPLACE(city, '''', '''''') || ''','''|| REPLACE(state_code, '''', '''''') || ''',''' || zip || ''');' from location;

SELECT 'INSERT INTO person VALUES (''' || REPLACE(first_name,'''', '''''') || ''',''' || REPLACE(middle_name,'''', '''''') || ''',''' || REPLACE(last_name,'''', '''''') || ''',''' || REPLACE(name_suffix,'''', '''''') || ''',''' || id || ''');' from person;

SELECT 'INSERT INTO physical_details VALUES (''' || person_id || ''',''' || REPLACE(sex,'''', '''''') || ''',''' || dob || ''',''' || height || ''',''' || weight || ''',''' || REPLACE(eye_color,'''', '''''') || ''',''' || REPLACE(hair_color,'''', '''''') || ''');' from physical_details;

SELECT 'INSERT INTO residence VALUES (''' || id || ''',''' || person_id || ''',''' || location_id || ''',''' || start_date || ''',''' || end_date || ''');' from residence;

SELECT 'INSERT INTO vehicle_registration VALUES (''' || id || ''',''' || REPLACE(tag_no,'''', '''''') || ''',''' || REPLACE(vin,'''', '''''') || ''',''' || REPLACE(make,'''', '''''') || ''',''' || REPLACE(model,'''', '''''') || ''',''' || year || ''','''|| expiration || ''',''' || REPLACE(color,'''', '''''') || ''');' from vehicle_registration;

SELECT 'INSERT INTO vehicle_owner VALUES (''' || person_id || ''',''' || vehicle_id || ''');' from vehicle_owner;


--SELECT 'INSERT INTO organization VALUES (''' || organizationid || ''',''' || REPLACE(REPLACE(organizationname1, '''', ''''''), '&', '&''||''') || ''',''' || REPLACE(REPLACE(organizationname2,'''', ''''''),'&', '&''||''') || ''',''' || REPLACE(REPLACE(organizationname3,'''', ''''''),'&', '&''||''') || ''',''' || locationid || ''');' from organization;

--SELECT 'INSERT INTO vehicleregistration VALUES (''' || vehicleregistrationid || ''',''' || REPLACE(registrationtypetext,'''', '''''') || ''',''' || REPLACE(statustext,'''', '''''') || ''',''' || REPLACE(decalperiodtext,'''', '''''') || ''',''' || registrationexpirationdate || ''',''' || REPLACE(registrationjurisdictioncode,'''', '''''') || ''',''' || REPLACE(vehicleregistrationplateid,'''', '''''') || ''',''' || REPLACE(vehicleregistrationplatetype,'''', '''''') || ''',''' || REPLACE(vehicleid,'''', '''''') || ''',''' || REPLACE(vehiclemakecodetext,'''', '''''') || ''',''' || REPLACE(vehiclemodelcodetext,'''', '''''') || ''',''' || vehiclemodelyeardate || ''',''' || REPLACE(vehiclecolorprimarytext,'''', '''''') || ''',''' || REPLACE(vehiclecolorsecondarytext,'''', '''''') || ''');' from vehicleregistration;

--SELECT 'INSERT INTO vehicleregistrationparty VALUES (''' || vehicleregistrationpartyid || ''',''' || vehicleregistrationid || ''','''|| registrationpartypersonid || ''',''' ||  registrationpartyorgid || ''');' from vehicleregistrationparty;

--SELECT 'INSERT INTO driverlicense VALUES(''' || REPLACE(driverlicensetypetext,'''', '''''') || ''',''' || driverauthorizationissuedate || ''',''' ||  driverauthorizationexpdate || ''',''' ||  personid || ''');' from driverlicense;
--);

--SELECT 'INSERT INTO driverhistory VALUES(''' || driverhistoryid || ''',''' || eventbegindate || ''',''' ||  eventenddate || ''',''' || REPLACE(eventtypetext,'''', '''''') || ''',''' || personid || ''');' from driverhistory;

SELECT 'COMMIT; ' from dual;

spool off;