package ejava.examples.orm.listeners.annotated;

import javax.persistence.*;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class provides an example of an entity that owns a OneToOne
 * uni-directional relationship joined by a @GeneratedValue primary
 * key. Since the primary key is generated by the provider, we cannot
 * assign a value to the associated object until we have been persisted.
 * We will use an Entity Callbacks to assign the associated Residence object
 * the owners primary key when assigned.
 *  
 * @author jcstaff
 *
 */
@Entity @Table(name="ORMLISTEN_PERSON")
//@EntityListeners(Listener.class) - enabled in deployment descriptor
public class Person {
    private static final Log log = LogFactory.getLog(Person.class);
    private static final Log cbLog = LogFactory.getLog("callback.Person");
    
    private long id;
    private String name;
    private Residence residence;
   
    protected Person() {}
    public Person(String name) {
        this.name = name;
    }
    public Person(long id, String name) {
        this.id = id;
        this.name = name;
    }
    
    public long peekId() { return id; } //peek at ID without logging
    
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE)
    //@GeneratedValue(strategy=GenerationType.TABLE) 
    //@GeneratedValue(strategy=GenerationType.IDENTITY)
    public long getId() {
        return id;
    }
    protected void setId(long id) {
        log.debug("Person.setId() called with:" + id);
        this.id = id;
        //if (residence != null && residence.peekId() == 0) { 
        //    residence.putId(id, "Person"); 
        //}
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    
    @OneToOne(mappedBy="person", optional=true, cascade=CascadeType.ALL)
    public Residence getResidence() {
        return residence;
    }
    public void setResidence(Residence residence) {        
        this.residence = residence;
        if (residence != null) {
        	residence.setPerson(this);
        }
    }
    
    @PrePersist public void prePersist() {
        cbLog.debug("Callback.prePersist event:" + this.toString());
    }
    @PostPersist public void postPersist() {
    	cbLog.debug("Callback.postPersist event:" + this.toString());
        if (residence.peekId() != 0) {
        	cbLog.debug("Person Callback.postPersist too late");
        }
        else if (residence != null && residence.peekId() == 0) { 
            residence.putId(id, "Listener"); 
        } 
        else {
        	cbLog.debug("Person Callback.postPersist too late");
        }
    }
    @PostLoad public void postLoad() {
    	cbLog.debug("Callback.postLoad event:" + this.toString());
    }
    @PreUpdate public void preUpdate() {
    	cbLog.debug("Callback.preUpdate event:" + this.toString());
    }
    @PostUpdate public void postUpdate() {
    	cbLog.debug("Callback.postUpdate event:" + this.toString());
    }
    @PreRemove public void preRemove() {
    	cbLog.debug("Callback.preRemove event:" + this.toString());
    }
    @PostRemove public void postRemove() {
    	cbLog.debug("Callback.postRemove event:" + this.toString());
    }
    
    public String toString() {
        StringBuilder text = new StringBuilder();
        text.append("person id=" + id);
        text.append(", name=" + name);
        text.append(", residence=" + residence);
        return text.toString();
    }
}
