package ejava.examples.orm.core.mapped;

/**
 * This class provides an example of a entity mapped to the database using 
 * a generated primary key AUTO-matically generated by the Java Persistence 
 * provider (i.e., not using the database for key value). This will be done
 * through the orm.xml mapping file.
 */
public class Drill {
    private long id;
    private String make;
    
    public Drill() {}
    public Drill(long id) { this.id = id; }
    
    public long getId() { return id; }

    public String getMake() { return make; }
    public void setMake(String make) {
        this.make = make;
    }
    
    public String toString() {
        return super.toString()
            + ", id=" + id
            + ", make=" + make;        
    }
}
