package ejava.examples.orm.core.mapped;

import java.io.Serializable;

/**
 * This class provides an example of a entity mapped to the database using 
 * a generated primary key AUTO-matically generated by the Java Persistance 
 * provider (i.e., not using the database for key value). This will be done
 * through the orm.xml mapping file.
 * 
 * @author jcstaff
 * $Id:$
 */
public class Drill implements Serializable {
    private static final long serialVersionUID = 1L;
    private long id=0;
    private String make;
    
    public Drill() {}
    public Drill(long id) { this.id = id; }
    
    public long getId() {
        return id;
    }
    @SuppressWarnings("unused")
    private void setId(long id) {
        this.id = id;
    }
    public String getMake() {
        return make;
    }
    public void setMake(String make) {
        this.make = make;
    }
    
    public String toString() {
        return super.toString()
            + ", id=" + id
            + ", make=" + make;        
    }
}
