package ejava.examples.orm.core.annotated;

import java.io.Serializable;

import javax.persistence.*;

/**
 * This class provides an example of a entity mapped to the database using 
 * a generated primary key AUTO-matically generated by the Java Persistance 
 * provider (i.e., not using the database for key value).
 * 
 * @author jcstaff
 * $Id:$
 */
@Entity
@Table(name="ORMCORE_DRILL")
public class Drill implements Serializable {
    private static final long serialVersionUID = 1L;
    private long id=0;
    private String make;
    
    public Drill() {}
    public Drill(long id) { this.id = id; }
    
    @Id
    @GeneratedValue( //AUTO is the default and could be left off here
            strategy=GenerationType.AUTO) 
    public long getId() {
        return id;
    }
    @SuppressWarnings("unused")
    private void setId(long id) {
        this.id = id;
    }
    public String getMake() {
        return make;
    }
    public void setMake(String make) {
        this.make = make;
    }
	@Override
	public String toString() {
		return new StringBuilder()
		          .append(super.toString())
		          .append(", id=").append(id)
		          .append(", make=").append(make)
		          .toString();
	}    
}
