DROP TABLE vehicle_owner;
DROP TABLE vehicle_registration;
DROP TABLE residence;
DROP TABLE location;
DROP TABLE physical_details;
DROP TABLE photo;
DROP TABLE person;

CREATE TABLE PERSON ( "FIRST_NAME" VARCHAR2(16) NOT NULL , "MIDDLE_NAME" VARCHAR2(16), "LAST_NAME" VARCHAR2(32) NOT NULL , "NAME_SUFFIX" VARCHAR2(16), "ID" INTEGER, CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID"));

CREATE TABLE PHOTO ( "IMAGE" BLOB NOT NULL , "PERSON_ID" INTEGER, CONSTRAINT "PHOTO_PERSON_FK1" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID"));

CREATE TABLE PHYSICAL_DETAILS ( "PERSON_ID" INTEGER, "SEX" VARCHAR2(1), "DOB" DATE, "HEIGHT" INTEGER, "WEIGHT" INTEGER, "EYE_COLOR" VARCHAR2(16), "HAIR_COLOR" VARCHAR2(16), CONSTRAINT "PHYSICAL_DETAILS_PERSON_FK1" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID"));

CREATE TABLE LOCATION ( "ID" INTEGER, "STREET_NO" VARCHAR2(16), "STREET_NAME" VARCHAR2(64), "CITY" VARCHAR2(64), "STATE_CODE" VARCHAR2(2), "ZIP" VARCHAR2(10), CONSTRAINT "LOCATION_PK" PRIMARY KEY ("ID") );


CREATE TABLE RESIDENCE ( "ID" INTEGER, "PERSON_ID" INTEGER, "LOCATION_ID" INTEGER, "START_DATE" DATE NOT NULL , "END_DATE" DATE, CONSTRAINT "RESIDENCE_LOCATION_FK1" FOREIGN KEY ("LOCATION_ID") REFERENCES "LOCATION" ("ID"));

CREATE TABLE VEHICLE_REGISTRATION ( "ID" INTEGER, "TAG_NO" VARCHAR2(10), "VIN" VARCHAR2(32), "MAKE" VARCHAR2(32), "MODEL" VARCHAR2(32), "YEAR" VARCHAR2(4000), "EXPIRATION" DATE, "COLOR" VARCHAR2(32), CONSTRAINT "VEHICLE_REGISTRATION_PK" PRIMARY KEY ("ID"));

CREATE TABLE VEHICLE_OWNER ( "PERSON_ID" INTEGER, "VEHICLE_ID" INTEGER, CONSTRAINT "VEHICLE_OWNER_PERSON_FK1" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID"));

COMMIT;