CREATE TABLE EM_AUTO (
    ID BIGINT generated by default as identity (start with 1) not null,
    MAKE VARCHAR(32),
    MODEL VARCHAR(32),
    COLOR VARCHAR(32),
    MILEAGE INT,

    CONSTRAINT em_autoPK PRIMARY KEY(ID)
)
